export const USER_INPUT_LOGIN_CHANGED = 'USER_INPUT_LOGIN_CHANGED';
export const USER_TRY_TO_LOG_IN = 'USER_TRY_TO_LOG_IN';
export const USER_TRY_TO_LOG_OUT = 'USER_TRY_TO_LOG_OUT';
export const USER_TRY_TO_REGISTRATE = 'USER_TRY_TO_REGISTRATE';
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const REGISTRATION_FAIL = 'REGISTRATION_FAIL';

export const GET_USERS_LOADING = 'GET_USERS_LOADING';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAIL = 'GET_USERS_FAIL';
export const GET_USER_POST_SUCCESS = 'GET_USER_POST_SUCCESS'
export const GET_EDIT_USERDATA = 'GET_EDIT_USERDATA';
export const SEND_EDIT_USERDATA_SUCCESS = 'POST_EDIT_USERDATA_SUCCESS';
export const LEAVE_USER_PAGE = 'LEAVE_USER_PAGE';
export const GET_DATA_FROM_STORAGE ='GET_DATA_FROM_STORAGE';
export const DELETE_USER = 'DELETE_USER';
export const UPLOAD_AVATAR = 'UPLOAD_AVATAR';

export const GET_POSTS_LOADING = 'GET_POST_LOADING';
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const GET_POSTS_FAIL = 'GET_POSTS_FAIL';
export const GET_ONE_POST_SUCCESS = 'GET_ONE_POST_SUCCESS';
export const GET_NEXT_POST_SUCCESS = 'GET_NEXT_POST_SUCCESS';
export const LEAVE_POSTS_PAGE = 'LEAVE_POSTS_PAGE';
export const SEND_POST_SUCCESS = 'SEND_POST_SUCCESS';
export const POST_DELETE_SUCCESS = 'POST_DELETE_SUCCESS';
export const RESET_DELETE_INDICATOR = 'RESET_DELETE_INDICATOR';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';


export const CREATE_COMMENT = 'POST_COMMENT';
export const CREATE_COMMENTS_FAIL = 'CREATE_COMMENTS_FAIL';

export const SET_ACTIVE_SELECT = 'SET_ACTIVE_SELECT';

export const SET_MODAL_STATE = 'SET_MODAL_STATE';

export const LOGIN_WAITING = 'LOGIN_WAITING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';


export const CREATE_LIKE = 'CREATE_LIKE';
export const CREATE_LIKE_ON_POST_PAGE = 'CREATE_LIKE_ON_POST_PAGE';