export const USER_INPUT_LOGIN_CHANGED = 'USER_INPUT_LOGIN_CHANGED';
export const USER_TRY_TO_LOG_IN = 'USER_TRY_TO_LOG_IN';
export const USER_TRY_TO_LOG_OUT = 'USER_TRY_TO_LOG_OUT';
export const GET_USERS_LOADING = 'GET_USERS_LOADING';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAIL = 'GET_USERS_FAIL';
